# Generated by Django 4.2.27 on 2026-01-04 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0004_remove_subscription_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('config', models.JSONField(default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_experiments', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='authentication.workspace')),
            ],
            options={
                'db_table': 'experiments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExperimentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('parameters', models.JSONField(default=dict)),
                ('metrics', models.JSONField(default=dict)),
                ('artifacts', models.JSONField(blank=True, default=list)),
                ('training_data', models.JSONField(blank=True, default=dict)),
                ('validation_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('git_commit', models.CharField(blank=True, max_length=40)),
                ('git_branch', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='data_science.experiment')),
                ('run_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiment_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'experiment_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('entity_name', models.CharField(max_length=255)),
                ('entity_key', models.CharField(max_length=255)),
                ('source_table', models.CharField(blank=True, max_length=1024)),
                ('transformation_query', models.TextField(blank=True)),
                ('features', models.JSONField(default=list)),
                ('online_enabled', models.BooleanField(default=False)),
                ('ttl_days', models.IntegerField(blank=True, null=True)),
                ('row_count', models.BigIntegerField(blank=True, null=True)),
                ('last_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_feature_groups', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_groups', to='authentication.workspace')),
            ],
            options={
                'db_table': 'feature_groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeatureView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('features', models.JSONField(default=list)),
                ('join_keys', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature_groups', models.ManyToManyField(related_name='feature_views', to='data_science.featuregroup')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_feature_views', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_views', to='authentication.workspace')),
            ],
            options={
                'db_table': 'feature_views',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('framework', models.CharField(choices=[('sklearn', 'Scikit-learn'), ('tensorflow', 'TensorFlow'), ('pytorch', 'PyTorch'), ('xgboost', 'XGBoost'), ('lightgbm', 'LightGBM'), ('custom', 'Custom')], max_length=50)),
                ('model_type', models.CharField(blank=True, max_length=100)),
                ('latest_version', models.IntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_models', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_models', to='authentication.workspace')),
            ],
            options={
                'db_table': 'ml_models',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingDataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('storage_path', models.CharField(max_length=1024)),
                ('format', models.CharField(default='parquet', max_length=20)),
                ('row_count', models.BigIntegerField(blank=True, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('splits', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_training_datasets', to=settings.AUTH_USER_MODEL)),
                ('feature_view', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_datasets', to='data_science.featureview')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_datasets', to='authentication.workspace')),
            ],
            options={
                'db_table': 'training_datasets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace'], name='training_da_workspa_055444_idx'), models.Index(fields=['feature_view'], name='training_da_feature_a9d1e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
                ('artifact_path', models.CharField(max_length=1024)),
                ('artifact_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('input_schema', models.JSONField(blank=True, default=dict)),
                ('output_schema', models.JSONField(blank=True, default=dict)),
                ('metrics', models.JSONField(default=dict)),
                ('stage', models.CharField(choices=[('none', 'None'), ('staging', 'Staging'), ('production', 'Production'), ('archived', 'Archived')], default='none', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experiment_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_versions', to='data_science.experimentrun')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='data_science.mlmodel')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_model_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'model_versions',
                'ordering': ['-version'],
                'indexes': [models.Index(fields=['model', '-version'], name='model_versi_model_i_4bc64e_idx'), models.Index(fields=['stage'], name='model_versi_stage_15a2a8_idx')],
                'unique_together': {('model', 'version')},
            },
        ),
        migrations.AddIndex(
            model_name='mlmodel',
            index=models.Index(fields=['workspace', 'framework'], name='ml_models_workspa_ff7426_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mlmodel',
            unique_together={('workspace', 'name')},
        ),
        migrations.AddIndex(
            model_name='featureview',
            index=models.Index(fields=['workspace'], name='feature_vie_workspa_510874_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='featureview',
            unique_together={('workspace', 'name')},
        ),
        migrations.AddIndex(
            model_name='featuregroup',
            index=models.Index(fields=['workspace', 'entity_name'], name='feature_gro_workspa_b0d68b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='featuregroup',
            unique_together={('workspace', 'name')},
        ),
        migrations.AddIndex(
            model_name='experimentrun',
            index=models.Index(fields=['experiment', '-created_at'], name='experiment__experim_20ac0d_idx'),
        ),
        migrations.AddIndex(
            model_name='experimentrun',
            index=models.Index(fields=['status'], name='experiment__status_9cbf76_idx'),
        ),
        migrations.AddIndex(
            model_name='experiment',
            index=models.Index(fields=['workspace', 'status'], name='experiments_workspa_213f6f_idx'),
        ),
        migrations.AddIndex(
            model_name='experiment',
            index=models.Index(fields=['owner'], name='experiments_owner_i_b46876_idx'),
        ),
    ]
