# Generated by Django 4.2.27 on 2026-01-04 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0004_remove_subscription_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=255)),
                ('layout', models.JSONField(blank=True, default=dict)),
                ('theme', models.CharField(default='light', max_length=50)),
                ('auto_refresh', models.BooleanField(default=False)),
                ('refresh_interval_seconds', models.IntegerField(default=300)),
                ('is_public', models.BooleanField(default=False)),
                ('is_template', models.BooleanField(default=False)),
                ('view_count', models.IntegerField(default=0)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dashboards', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_dashboards', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='authentication.workspace')),
            ],
            options={
                'db_table': 'dashboards',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source_type', models.CharField(choices=[('dashboard', 'Dashboard'), ('query', 'Query'), ('custom', 'Custom')], max_length=20)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('html', 'HTML')], default='pdf', max_length=20)),
                ('schedule', models.CharField(blank=True, max_length=255)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('delivery_method', models.CharField(choices=[('email', 'Email'), ('slack', 'Slack'), ('storage', 'Storage')], default='email', max_length=20)),
                ('delivery_config', models.JSONField(default=dict)),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
                ('last_delivered_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='analytics.dashboard')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('widget_type', models.CharField(choices=[('line_chart', 'Line Chart'), ('bar_chart', 'Bar Chart'), ('pie_chart', 'Pie Chart'), ('area_chart', 'Area Chart'), ('scatter_plot', 'Scatter Plot'), ('table', 'Table'), ('metric', 'Metric'), ('text', 'Text'), ('map', 'Map'), ('heatmap', 'Heatmap'), ('gauge', 'Gauge')], max_length=50)),
                ('query_id', models.UUIDField(blank=True, null=True)),
                ('query_text', models.TextField(blank=True)),
                ('data_source', models.JSONField(blank=True, default=dict)),
                ('config', models.JSONField(default=dict)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=6)),
                ('height', models.IntegerField(default=4)),
                ('cache_duration_seconds', models.IntegerField(default=300)),
                ('last_cached_at', models.DateTimeField(blank=True, null=True)),
                ('cached_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='analytics.dashboard')),
            ],
            options={
                'db_table': 'widgets',
                'ordering': ['position_y', 'position_x'],
            },
        ),
        migrations.CreateModel(
            name='SavedQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('query_text', models.TextField()),
                ('catalog', models.CharField(default='iceberg', max_length=100)),
                ('schema_name', models.CharField(blank=True, max_length=100)),
                ('parameters', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('folder', models.CharField(blank=True, max_length=255)),
                ('is_public', models.BooleanField(default=False)),
                ('execution_count', models.IntegerField(default=0)),
                ('last_executed_at', models.DateTimeField(blank=True, null=True)),
                ('avg_execution_time_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_queries', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_queries', to='authentication.workspace')),
            ],
            options={
                'verbose_name_plural': 'Saved queries',
                'db_table': 'saved_queries',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('file_url', models.URLField(blank=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('delivery_error', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='analytics.report')),
            ],
            options={
                'db_table': 'report_executions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='query',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='analytics.savedquery'),
        ),
        migrations.AddField(
            model_name='report',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='authentication.workspace'),
        ),
        migrations.CreateModel(
            name='Exploration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('state', models.JSONField(default=dict)),
                ('source_type', models.CharField(blank=True, max_length=50)),
                ('source_reference', models.CharField(blank=True, max_length=1024)),
                ('cell_count', models.IntegerField(default=0)),
                ('last_cell_executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explorations', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explorations', to='authentication.workspace')),
            ],
            options={
                'db_table': 'explorations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='savedquery',
            index=models.Index(fields=['workspace', 'owner'], name='saved_queri_workspa_838a3a_idx'),
        ),
        migrations.AddIndex(
            model_name='savedquery',
            index=models.Index(fields=['is_public'], name='saved_queri_is_publ_4f373e_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['report', '-created_at'], name='report_exec_report__30d22b_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['status'], name='report_exec_status_c1b883_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['workspace', 'enabled'], name='reports_workspa_c1914a_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['next_run_at'], name='reports_next_ru_ae4deb_idx'),
        ),
        migrations.AddIndex(
            model_name='exploration',
            index=models.Index(fields=['workspace', 'user'], name='exploration_workspa_30c72d_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['workspace', 'owner'], name='dashboards_workspa_063161_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['is_public'], name='dashboards_is_publ_3ef35f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dashboard',
            unique_together={('workspace', 'slug')},
        ),
    ]
