# Generated by Django 4.2.27 on 2025-12-30 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_plan_workspace_subscription_invoice_apikey_workspace_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('zone_type', models.CharField(choices=[('hot', 'Hot Storage - SSD'), ('warm', 'Warm Storage - HDD'), ('cold', 'Cold Storage - Archive')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('total_capacity', models.BigIntegerField(help_text='Total capacity in bytes')),
                ('used_storage', models.BigIntegerField(default=0, help_text='Used storage in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_zones', to='authentication.workspace')),
            ],
            options={
                'ordering': ['zone_type'],
            },
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='v1.0', max_length=50)),
                ('schema_definition', models.JSONField(blank=True, default=dict, help_text='JSON schema definition')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schemas', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_lake_schemas', to='authentication.workspace')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('workspace', 'name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='data_lake.folder')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_lake_folders', to='authentication.workspace')),
            ],
            options={
                'ordering': ['path'],
                'unique_together': {('workspace', 'path')},
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=1024)),
                ('format', models.CharField(choices=[('parquet', 'Parquet'), ('csv', 'CSV'), ('json', 'JSON'), ('avro', 'Avro'), ('orc', 'ORC'), ('delta', 'Delta Lake'), ('table', 'Table')], max_length=20)),
                ('size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('rows', models.BigIntegerField(blank=True, help_text='Number of records', null=True)),
                ('columns', models.IntegerField(blank=True, help_text='Number of columns', null=True)),
                ('storage_url', models.CharField(blank=True, help_text='S3/MinIO storage URL', max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='data_lake.folder')),
                ('schema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='data_lake.schema')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_lake_files', to='authentication.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('workspace', 'path')},
            },
        ),
    ]
