# Generated by Django 4.2.27 on 2025-12-22 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0002_plan_workspace_subscription_invoice_apikey_workspace_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('mongodb', 'MongoDB'), ('s3', 'Amazon S3'), ('kafka', 'Apache Kafka'), ('api', 'REST API'), ('salesforce', 'Salesforce'), ('snowflake', 'Snowflake'), ('bigquery', 'Google BigQuery'), ('redshift', 'Amazon Redshift')], max_length=50)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('database', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password_encrypted', models.TextField(blank=True)),
                ('ssl', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error')], default='inactive', max_length=50)),
                ('last_tested', models.DateTimeField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_connections', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='authentication.workspace')),
            ],
            options={
                'db_table': 'connections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('paused', 'Paused'), ('failed', 'Failed'), ('success', 'Success'), ('idle', 'Idle')], default='idle', max_length=50)),
                ('schedule', models.CharField(blank=True, max_length=255)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('run_count', models.IntegerField(default=0)),
                ('success_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('records_processed', models.BigIntegerField(default=0)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pipelines', to=settings.AUTH_USER_MODEL)),
                ('destination_connection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_pipelines', to='integration.connection')),
                ('source_connection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_pipelines', to='integration.connection')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='authentication.workspace')),
            ],
            options={
                'db_table': 'pipelines',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('tables', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='disconnected', max_length=50)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('record_count', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='integration.connection')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='authentication.workspace')),
            ],
            options={
                'db_table': 'data_sources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cron_expression', models.CharField(max_length=255)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_config', to='integration.pipeline')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='authentication.workspace')),
            ],
            options={
                'db_table': 'schedules',
                'ordering': ['next_run'],
                'indexes': [models.Index(fields=['workspace', 'enabled'], name='schedules_workspa_eddc6a_idx'), models.Index(fields=['next_run'], name='schedules_next_ru_4d7a31_idx')],
            },
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('records_processed', models.BigIntegerField(default=0)),
                ('bytes_processed', models.BigIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('triggered_by', models.CharField(choices=[('manual', 'Manual'), ('schedule', 'Schedule'), ('api', 'API')], default='manual', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='integration.pipeline')),
                ('triggered_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_pipeline_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pipeline_runs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['pipeline', '-created_at'], name='pipeline_ru_pipelin_b21bcc_idx'), models.Index(fields=['status'], name='pipeline_ru_status_2854f1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='pipeline',
            index=models.Index(fields=['workspace', 'status'], name='pipelines_workspa_882c29_idx'),
        ),
        migrations.AddIndex(
            model_name='pipeline',
            index=models.Index(fields=['created_by'], name='pipelines_created_0aab63_idx'),
        ),
        migrations.AddIndex(
            model_name='pipeline',
            index=models.Index(fields=['status'], name='pipelines_status_aecf1f_idx'),
        ),
        migrations.AddIndex(
            model_name='datasource',
            index=models.Index(fields=['workspace', 'status'], name='data_source_workspa_9b5a48_idx'),
        ),
        migrations.AddIndex(
            model_name='datasource',
            index=models.Index(fields=['connection'], name='data_source_connect_5be51d_idx'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['workspace', 'status'], name='connections_workspa_2a8634_idx'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['type'], name='connections_type_b843e3_idx'),
        ),
    ]
