# Generated by Django 4.2.27 on 2026-01-02 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0004_remove_subscription_plan_and_more'),
        ('integration', '0003_rename_connection_to_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='source',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='workspace',
        ),
        migrations.RenameIndex(
            model_name='source',
            new_name='sources_workspa_7011b1_idx',
            old_name='connections_workspa_2a8634_idx',
        ),
        migrations.RenameIndex(
            model_name='source',
            new_name='sources_type_6fce03_idx',
            old_name='connections_type_b843e3_idx',
        ),
        migrations.AlterField(
            model_name='source',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='source',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='authentication.workspace'),
        ),
        migrations.DeleteModel(
            name='DataSource',
        ),
    ]
