# Generated by Django 4.2.27 on 2026-01-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0004_remove_datasource_source_remove_datasource_workspace_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceCatalog',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('api', 'API'), ('database', 'Database'), ('cloud', 'Cloud Storage'), ('file', 'File System')], max_length=20)),
                ('description', models.TextField()),
                ('auth_types', models.JSONField(default=list)),
                ('documentation', models.URLField(max_length=500)),
                ('popular', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'source_catalog',
                'ordering': ['-popular', 'name'],
            },
        ),
    ]
