# Generated by Django 4.2.27 on 2026-01-04 19:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0005_sourcecatalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedPipelineRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_id', models.CharField(db_index=True, max_length=255)),
                ('pipeline_id', models.UUIDField(db_index=True)),
                ('pipeline_run_id', models.UUIDField(db_index=True)),
                ('stream', models.CharField(max_length=255)),
                ('data', models.JSONField(default=dict)),
                ('error_message', models.TextField()),
                ('error_type', models.CharField(max_length=255)),
                ('error_traceback', models.TextField(blank=True)),
                ('attempt_count', models.IntegerField(default=1)),
                ('max_retries', models.IntegerField(default=3)),
                ('status', models.CharField(choices=[('pending', 'Pending Retry'), ('retrying', 'Retrying'), ('recovered', 'Recovered'), ('abandoned', 'Abandoned')], default='pending', max_length=20)),
                ('first_failed_at', models.DateTimeField()),
                ('last_failed_at', models.DateTimeField()),
                ('recovered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'failed_pipeline_records',
                'ordering': ['-last_failed_at'],
                'indexes': [models.Index(fields=['pipeline_id', 'status'], name='failed_pipe_pipelin_1c7301_idx'), models.Index(fields=['pipeline_run_id'], name='failed_pipe_pipelin_f705e9_idx'), models.Index(fields=['status', '-last_failed_at'], name='failed_pipe_status_5adb0f_idx')],
            },
        ),
    ]
