# Generated by Django 4.2.27 on 2026-01-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0006_failedpipelinerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='schedule_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('hourly', 'Every N Hours'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('cron', 'Custom (Cron)')], default='daily', max_length=20),
        ),
    ]
