# Generated by Django 4.2.27 on 2026-01-04 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0004_remove_subscription_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source_type', models.CharField(choices=[('kafka', 'Apache Kafka'), ('kinesis', 'AWS Kinesis'), ('pubsub', 'Google Pub/Sub'), ('eventhub', 'Azure Event Hub'), ('webhook', 'Webhook'), ('websocket', 'WebSocket')], max_length=50)),
                ('connection_config', models.JSONField(default=dict)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('consumer_group', models.CharField(blank=True, max_length=255)),
                ('schema_type', models.CharField(blank=True, max_length=50)),
                ('schema_registry_url', models.URLField(blank=True)),
                ('schema_definition', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error')], default='inactive', max_length=20)),
                ('last_connected', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stream_sources', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_sources', to='authentication.workspace')),
            ],
            options={
                'db_table': 'stream_sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StreamPipeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('destination_type', models.CharField(choices=[('lakehouse', 'Lakehouse'), ('database', 'Database'), ('stream', 'Stream'), ('webhook', 'Webhook')], max_length=20)),
                ('destination_config', models.JSONField(default=dict)),
                ('processing_config', models.JSONField(default=dict)),
                ('transformations', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('stopped', 'Stopped'), ('starting', 'Starting'), ('running', 'Running'), ('stopping', 'Stopping'), ('error', 'Error')], default='stopped', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('worker_id', models.CharField(blank=True, max_length=255, null=True)),
                ('messages_processed', models.BigIntegerField(default=0)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('error_count', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stream_pipelines', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='streaming.streamsource')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_pipelines', to='authentication.workspace')),
            ],
            options={
                'db_table': 'stream_pipelines',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StreamEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(max_length=255)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('event_time', models.DateTimeField()),
                ('key', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField()),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('partition', models.IntegerField(blank=True, null=True)),
                ('offset', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='streaming.streampipeline')),
            ],
            options={
                'db_table': 'stream_events',
                'ordering': ['-event_time'],
            },
        ),
        migrations.CreateModel(
            name='StreamCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('partition', models.IntegerField(default=0)),
                ('offset', models.BigIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('state_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='streaming.streampipeline')),
            ],
            options={
                'db_table': 'stream_checkpoints',
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='StreamAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('lag', 'Consumer Lag'), ('throughput', 'Throughput Drop'), ('error_rate', 'High Error Rate'), ('latency', 'High Latency'), ('anomaly', 'Data Anomaly'), ('schema', 'Schema Change')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('metric_value', models.FloatField(blank=True, null=True)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='streaming.streampipeline')),
            ],
            options={
                'db_table': 'stream_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='streamsource',
            index=models.Index(fields=['workspace', 'status'], name='stream_sour_workspa_25e102_idx'),
        ),
        migrations.AddIndex(
            model_name='streamsource',
            index=models.Index(fields=['source_type'], name='stream_sour_source__52613f_idx'),
        ),
        migrations.AddIndex(
            model_name='streampipeline',
            index=models.Index(fields=['workspace', 'status'], name='stream_pipe_workspa_92902c_idx'),
        ),
        migrations.AddIndex(
            model_name='streampipeline',
            index=models.Index(fields=['source'], name='stream_pipe_source__065b68_idx'),
        ),
        migrations.AddIndex(
            model_name='streamevent',
            index=models.Index(fields=['pipeline', '-event_time'], name='stream_even_pipelin_c6f784_idx'),
        ),
        migrations.AddIndex(
            model_name='streamevent',
            index=models.Index(fields=['event_id'], name='stream_even_event_i_f6d8e1_idx'),
        ),
        migrations.AddIndex(
            model_name='streamevent',
            index=models.Index(fields=['status'], name='stream_even_status_0af2e1_idx'),
        ),
        migrations.AddIndex(
            model_name='streamcheckpoint',
            index=models.Index(fields=['pipeline', 'partition', '-created_at'], name='stream_chec_pipelin_518236_idx'),
        ),
        migrations.AddIndex(
            model_name='streamalert',
            index=models.Index(fields=['pipeline', 'status', '-created_at'], name='stream_aler_pipelin_5b6df3_idx'),
        ),
        migrations.AddIndex(
            model_name='streamalert',
            index=models.Index(fields=['alert_type', 'severity'], name='stream_aler_alert_t_d2f7ba_idx'),
        ),
    ]
