# Generated by Django 4.2.27 on 2026-01-04 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0004_remove_subscription_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('qualified_name', models.CharField(max_length=1024, unique=True)),
                ('description', models.TextField(blank=True)),
                ('asset_type', models.CharField(choices=[('table', 'Table'), ('view', 'View'), ('file', 'File'), ('stream', 'Stream'), ('dashboard', 'Dashboard'), ('report', 'Report')], max_length=50)),
                ('catalog', models.CharField(blank=True, max_length=255)),
                ('schema_name', models.CharField(blank=True, max_length=255)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('row_count', models.BigIntegerField(blank=True, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('column_count', models.IntegerField(blank=True, null=True)),
                ('sensitivity', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted', 'Restricted')], default='internal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_assets', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_assets', to='authentication.workspace')),
            ],
            options={
                'db_table': 'data_assets',
                'ordering': ['qualified_name'],
            },
        ),
        migrations.CreateModel(
            name='DataQualityRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('column_name', models.CharField(blank=True, max_length=255)),
                ('rule_type', models.CharField(choices=[('not_null', 'Not Null'), ('unique', 'Unique'), ('range', 'Range Check'), ('regex', 'Regex Pattern'), ('enum', 'Enumeration'), ('referential', 'Referential Integrity'), ('custom_sql', 'Custom SQL'), ('freshness', 'Freshness'), ('volume', 'Volume Check')], max_length=20)),
                ('config', models.JSONField(default=dict)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('threshold', models.FloatField(default=100.0)),
                ('enabled', models.BooleanField(default=True)),
                ('schedule', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quality_rules', to=settings.AUTH_USER_MODEL)),
                ('data_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_rules', to='governance.dataasset')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_rules', to='authentication.workspace')),
            ],
            options={
                'db_table': 'data_quality_rules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataQualityResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('executed_at', models.DateTimeField()),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('warning', 'Warning'), ('error', 'Error')], max_length=20)),
                ('total_rows', models.BigIntegerField(blank=True, null=True)),
                ('passed_rows', models.BigIntegerField(blank=True, null=True)),
                ('failed_rows', models.BigIntegerField(blank=True, null=True)),
                ('pass_rate', models.FloatField(blank=True, null=True)),
                ('failure_samples', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='governance.dataqualityrule')),
            ],
            options={
                'db_table': 'governance_quality_results',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='DataLineage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lineage_type', models.CharField(choices=[('direct', 'Direct'), ('transform', 'Transform'), ('aggregate', 'Aggregate'), ('filter', 'Filter'), ('join', 'Join'), ('derive', 'Derive')], default='direct', max_length=20)),
                ('pipeline_id', models.UUIDField(blank=True, null=True)),
                ('pipeline_run_id', models.UUIDField(blank=True, null=True)),
                ('transformation', models.JSONField(blank=True, default=dict)),
                ('column_mappings', models.JSONField(blank=True, default=list)),
                ('confidence', models.FloatField(default=1.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downstream_lineage', to='governance.dataasset')),
                ('target_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upstream_lineage', to='governance.dataasset')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineage_edges', to='authentication.workspace')),
            ],
            options={
                'db_table': 'data_lineage',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('policy_type', models.CharField(choices=[('access', 'Access Control'), ('retention', 'Data Retention'), ('masking', 'Data Masking'), ('encryption', 'Encryption'), ('audit', 'Audit')], max_length=20)),
                ('rules', models.JSONField(default=list)),
                ('applies_to_tags', models.JSONField(blank=True, default=list)),
                ('enabled', models.BooleanField(default=True)),
                ('compliance_frameworks', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applies_to', models.ManyToManyField(blank=True, related_name='policies', to='governance.dataasset')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policies', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='authentication.workspace')),
            ],
            options={
                'verbose_name_plural': 'Policies',
                'db_table': 'policies',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['workspace', 'enabled'], name='policies_workspa_554a4f_idx'), models.Index(fields=['policy_type'], name='policies_policy__66f050_idx')],
            },
        ),
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('synonyms', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('approved', 'Approved'), ('deprecated', 'Deprecated')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_terms', to=settings.AUTH_USER_MODEL)),
                ('related_terms', models.ManyToManyField(blank=True, to='governance.glossaryterm')),
                ('steward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steward_terms', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glossary_terms', to='authentication.workspace')),
            ],
            options={
                'db_table': 'glossary_terms',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['workspace', 'status'], name='glossary_te_workspa_c66425_idx'), models.Index(fields=['category'], name='glossary_te_categor_56d2ce_idx')],
                'unique_together': {('workspace', 'name')},
            },
        ),
        migrations.AddIndex(
            model_name='dataqualityrule',
            index=models.Index(fields=['workspace', 'enabled'], name='data_qualit_workspa_ce823d_idx'),
        ),
        migrations.AddIndex(
            model_name='dataqualityrule',
            index=models.Index(fields=['data_asset'], name='data_qualit_data_as_0b6841_idx'),
        ),
        migrations.AddIndex(
            model_name='dataqualityrule',
            index=models.Index(fields=['rule_type'], name='data_qualit_rule_ty_eae91a_idx'),
        ),
        migrations.AddIndex(
            model_name='dataqualityresult',
            index=models.Index(fields=['rule', '-executed_at'], name='governance__rule_id_a47269_idx'),
        ),
        migrations.AddIndex(
            model_name='dataqualityresult',
            index=models.Index(fields=['status'], name='governance__status_a85bd7_idx'),
        ),
        migrations.AddIndex(
            model_name='datalineage',
            index=models.Index(fields=['source_asset'], name='data_lineag_source__d223b2_idx'),
        ),
        migrations.AddIndex(
            model_name='datalineage',
            index=models.Index(fields=['target_asset'], name='data_lineag_target__867b1d_idx'),
        ),
        migrations.AddIndex(
            model_name='datalineage',
            index=models.Index(fields=['pipeline_id'], name='data_lineag_pipelin_a7927e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='datalineage',
            unique_together={('source_asset', 'target_asset', 'lineage_type')},
        ),
        migrations.AddIndex(
            model_name='dataasset',
            index=models.Index(fields=['workspace', 'asset_type'], name='data_assets_workspa_d80974_idx'),
        ),
        migrations.AddIndex(
            model_name='dataasset',
            index=models.Index(fields=['qualified_name'], name='data_assets_qualifi_eccf3b_idx'),
        ),
        migrations.AddIndex(
            model_name='dataasset',
            index=models.Index(fields=['owner'], name='data_assets_owner_i_8b0eaa_idx'),
        ),
    ]
