# Generated by Django 4.2.27 on 2025-12-22 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_plan_workspace_subscription_invoice_apikey_workspace_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataQualityCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('check_type', models.CharField(choices=[('completeness', 'Completeness'), ('uniqueness', 'Uniqueness'), ('validity', 'Validity'), ('consistency', 'Consistency'), ('accuracy', 'Accuracy'), ('custom', 'Custom SQL')], max_length=50)),
                ('target_table', models.CharField(blank=True, max_length=255)),
                ('target_column', models.CharField(blank=True, max_length=255)),
                ('rule', models.TextField()),
                ('threshold', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], default='warning', max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('last_result', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quality_checks', to=settings.AUTH_USER_MODEL)),
                ('pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='integration.pipeline')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='authentication.workspace')),
            ],
            options={
                'db_table': 'data_quality_checks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transformation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('filter', 'Filter'), ('map', 'Map'), ('aggregate', 'Aggregate'), ('join', 'Join'), ('pivot', 'Pivot'), ('unpivot', 'Unpivot'), ('custom', 'Custom')], max_length=50)),
                ('config', models.JSONField(default=dict)),
                ('input_schema', models.JSONField(blank=True, default=dict)),
                ('output_schema', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error')], default='active', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('records_processed', models.BigIntegerField(default=0)),
                ('avg_execution_time', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transformations', to=settings.AUTH_USER_MODEL)),
                ('pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transformations', to='integration.pipeline')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformations', to='authentication.workspace')),
            ],
            options={
                'db_table': 'transformations',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataQualityResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('error', 'Error')], max_length=50)),
                ('total_records', models.BigIntegerField(default=0)),
                ('passed_records', models.BigIntegerField(default=0)),
                ('failed_records', models.BigIntegerField(default=0)),
                ('pass_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('execution_time', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('quality_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='transformation.dataqualitycheck')),
            ],
            options={
                'db_table': 'data_quality_results',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='TransformationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('rule_type', models.CharField(choices=[('rename', 'Rename Column'), ('cast', 'Cast Type'), ('calculate', 'Calculate Field'), ('filter', 'Filter Rows'), ('replace', 'Replace Values'), ('split', 'Split Column'), ('merge', 'Merge Columns'), ('custom', 'Custom Expression')], max_length=50)),
                ('config', models.JSONField(default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='transformation.transformation')),
            ],
            options={
                'db_table': 'transformation_rules',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['transformation', 'enabled'], name='transformat_transfo_d423b8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='transformation',
            index=models.Index(fields=['workspace', 'status'], name='transformat_workspa_b07eb4_idx'),
        ),
        migrations.AddIndex(
            model_name='transformation',
            index=models.Index(fields=['pipeline'], name='transformat_pipelin_d5419a_idx'),
        ),
        migrations.AddIndex(
            model_name='transformation',
            index=models.Index(fields=['type'], name='transformat_type_900893_idx'),
        ),
        migrations.AddIndex(
            model_name='dataqualityresult',
            index=models.Index(fields=['quality_check', '-executed_at'], name='data_qualit_quality_74c066_idx'),
        ),
        migrations.AddIndex(
            model_name='dataqualityresult',
            index=models.Index(fields=['result'], name='data_qualit_result_6b77b3_idx'),
        ),
        migrations.AddIndex(
            model_name='dataqualitycheck',
            index=models.Index(fields=['workspace', 'enabled'], name='data_qualit_workspa_9fb24e_idx'),
        ),
        migrations.AddIndex(
            model_name='dataqualitycheck',
            index=models.Index(fields=['pipeline'], name='data_qualit_pipelin_df4ecb_idx'),
        ),
        migrations.AddIndex(
            model_name='dataqualitycheck',
            index=models.Index(fields=['check_type'], name='data_qualit_check_t_b6c678_idx'),
        ),
    ]
