# Generated by Django 4.2.27 on 2026-01-04 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0004_remove_subscription_plan_and_more'),
        ('transformation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(choices=[('python', 'Python'), ('sql', 'SQL'), ('r', 'R')], default='python', max_length=50)),
                ('kernel', models.CharField(default='Python 3.11', max_length=100)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('cell_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('error', 'Error')], default='idle', max_length=50)),
                ('last_executed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notebooks', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebooks', to='authentication.workspace')),
            ],
            options={
                'db_table': 'notebooks',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['workspace', 'language'], name='notebooks_workspa_1cdf80_idx'), models.Index(fields=['created_by'], name='notebooks_created_fa7bee_idx')],
            },
        ),
    ]
