# Generated by Django 4.2.27 on 2026-01-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformation', '0002_notebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='framework',
            field=models.CharField(choices=[('scikit-learn', 'Scikit-learn'), ('tensorflow', 'TensorFlow'), ('pytorch', 'PyTorch'), ('huggingface', 'HuggingFace'), ('xgboost', 'XGBoost'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
